# AWS リージョンは user_data から -e aws_region=... で渡す（デフォルトは Osaka）
aws_region: "{{ aws_region | default('ap-northeast-3') }}"

# ---- SSM Parameter Store から取得（見つからなくても致命的にせず警告/スキップ）----
moodle_siteurl:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/alb/url',  region=aws_region, on_missing='warn') }}"
moodle_db_host_ssm: "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/host',    region=aws_region, on_missing='skip') | default('', true) }}"
moodle_db_host_alt: "{{ lookup('amazon.aws.aws_ssm', '/moodle/rds/endpoint', region=aws_region, on_missing='skip') | default('', true) }}"
moodle_db_name:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/name', region=aws_region, on_missing='warn') }}"
moodle_db_user:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/user', region=aws_region, on_missing='warn') }}"
moodle_efs_id:   "{{ lookup('amazon.aws.aws_ssm', '/moodle/efs/id',  region=aws_region, on_missing='warn') }}"

# Secrets Manager: /moodle/db/password
# 文字列を想定。もしJSONで入れている場合は自動でpasswordキーを拾う。
moodle_db_password_raw: "{{ lookup('amazon.aws.aws_secret',
                                   '/moodle/db/password',
                                   region=aws_region,
                                   on_missing='warn',
                                   on_denied='warn') | default('', true) }}"

# JSONなら .password を、そうでなければ生文字列を使う
moodle_db_password: >-
  {{ (moodle_db_password_raw | default('', true) | regex_search('^\\s*\\{'))
      and ((moodle_db_password_raw | from_json).password | default(moodle_db_password_raw, true))
      or moodle_db_password_raw }}

# ---- 環境変数や -e での上書きも許可 ----
moodle_db_host_env: "{{ lookup('ansible.builtin.env', 'MOODLE_DB_HOST', default='') }}"

# ディレクトリ・バージョンなど
moodle_wwwroot: "/var/www/moodle"
moodle_datadir: "/var/moodledata"      # EFS マウントターゲット
moodle_branch:  "MOODLE_405_STABLE"    # 必要に応じて変更
moodle_web_user:  "www-data"
moodle_web_group: "www-data"

moodle_trusted_proxy_cidrs:
  - "10.81.16.0/20"
  - "10.81.32.0/20"
