# AWS リージョンは user_data から -e aws_region=... で渡す（デフォルトは Osaka）
aws_region: "{{ aws_region | default('ap-northeast-3') }}"

# ---- SSM Parameter Store から取得（見つからなくても致命的にせず警告/スキップ）----
moodle_siteurl:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/alb/url',  region=aws_region, on_missing='warn') }}"
moodle_db_host_ssm: "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/host',    region=aws_region, on_missing='skip') | default('', true) }}"
moodle_db_host_alt: "{{ lookup('amazon.aws.aws_ssm', '/moodle/rds/endpoint', region=aws_region, on_missing='skip') | default('', true) }}"
moodle_db_name:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/name', region=aws_region, on_missing='warn') }}"
moodle_db_user:  "{{ lookup('amazon.aws.aws_ssm', '/moodle/db/user', region=aws_region, on_missing='warn') }}"
moodle_efs_id:   "{{ lookup('amazon.aws.aws_ssm', '/moodle/efs/id',  region=aws_region, on_missing='warn') }}"

# ---- Secrets Manager から取得（戻り値は dict）----
moodle_db_password: >-
  {{ (lookup('amazon.aws.aws_secret', '/moodle/db/password', region=aws_region) | default({}, true)).get('SecretString', '') }}

# ---- 環境変数や -e での上書きも許可 ----
moodle_db_host_env: "{{ lookup('ansible.builtin.env', 'MOODLE_DB_HOST', default='') }}"

# ディレクトリ・バージョンなど
moodle_wwwroot: "/var/www/moodle"
moodle_datadir: "/var/moodledata"      # EFS マウントターゲット
moodle_branch:  "MOODLE_401_STABLE"    # 必要に応じて変更
moodle_web_user:  "www-data"
moodle_web_group: "www-data"
